exclude_paths:
  - tmp
  - vendor

detectors:
  LongParameterList:
    enabled: false
  NestedIterators:
    exclude:
      - "Transactable::Pipeable#define_steps"
  TooManyStatements:
    exclude:
      - "Transactable::Pipeable#define_pipe"
      - "Transactable::Pipeable#define_steps"
  UtilityFunction:
    exclude:
      - "FastComposer#fetch"
      - "FastComposer#multiply"
      - "FastComposer#round"
